// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/all_assets": {
            "get": {
                "description": "查询所有素材的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "素材"
                ],
                "summary": "获取所有素材",
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.AssetsResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Asset_ids": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.Asset"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/all_songs": {
            "get": {
                "description": "查询所有歌曲信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌曲"
                ],
                "summary": "获取所有歌曲",
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/response.SongsResponse"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "Song_ids": {
                                                            "type": "array",
                                                            "items": {
                                                                "$ref": "#/definitions/models.Song"
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/asset": {
            "get": {
                "description": "根据传入的 asset_id 查询素材的 file_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "素材"
                ],
                "summary": "获取单个素材",
                "parameters": [
                    {
                        "type": "string",
                        "description": "素材ID",
                        "name": "asset_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.AssetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/essay": {
            "get": {
                "description": "根据传入的 topic 参数，通过 gRPC 流式调用生成文章，并使用 SSE 向前端实时推送生成结果",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "文章",
                    "SSE",
                    "gRPC"
                ],
                "summary": "获取生成的文章",
                "parameters": [
                    {
                        "type": "string",
                        "description": "生成文章的主题",
                        "name": "topic",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/get_context": {
            "get": {
                "description": "根据问题的标题获取其内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题"
                ],
                "summary": "根据标题获取内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "问题标题",
                        "name": "title",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/get_list": {
            "get": {
                "description": "获取所有问题的标题列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题"
                ],
                "summary": "获取问题标题列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/get_upload_token": {
            "get": {
                "description": "验证用户令牌并返回上传令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "上传"
                ],
                "summary": "获取上传令牌",
                "parameters": [
                    {
                        "description": "用户验证令牌",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.VerifyToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.UploadToken"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/save_question": {
            "post": {
                "description": "保存一个包含标题和内容的问题",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问题"
                ],
                "summary": "保存问题",
                "parameters": [
                    {
                        "description": "问题数据",
                        "name": "question",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Question"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/score": {
            "post": {
                "description": "接收 JSON 格式的总分数据并上传到服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分数"
                ],
                "summary": "上传总分",
                "parameters": [
                    {
                        "description": "上传的总分信息",
                        "name": "totalScore",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ScoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/scores": {
            "get": {
                "description": "根据传入的 song_id 查询该歌曲所有的总分记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分数"
                ],
                "summary": "获取歌曲所有总分信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "歌曲ID",
                        "name": "song_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.ScoreReponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/song": {
            "get": {
                "description": "根据传入的 song_id 查询歌曲信息并返回文件ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌曲"
                ],
                "summary": "获取歌曲信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "歌曲ID",
                        "name": "song_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.SongResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/update_list_asset": {
            "get": {
                "description": "更新素材列表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "素材"
                ],
                "summary": "更新素材列表",
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/update_list_song": {
            "get": {
                "description": "更新歌曲列表信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "歌曲"
                ],
                "summary": "更新歌曲列表",
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/user_scores": {
            "get": {
                "description": "根据传入的 user_id 查询该用户所有的最佳分数记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分数"
                ],
                "summary": "获取用户所有最佳成绩",
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/response.ScoreReponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/forget_password": {
            "get": {
                "description": "用户通过邮箱请求密码重置，会收到包含重置链接的邮件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "请求密码重置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户注册邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户登录，验证用户名和密码，生成 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录接口",
                "parameters": [
                    {
                        "description": "用户登录信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "用户注册接口，接收用户信息创建新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/reset_password": {
            "get": {
                "description": "用户通过邮件中提供的 token 进行密码重置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "重置密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "密码重置令牌",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户注册邮箱",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "new_password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/send_code": {
            "get": {
                "description": "生成并向用户邮箱发送验证码",
                "tags": [
                    "Verification"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "邮箱地址",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/verify_code": {
            "post": {
                "description": "验证用户提交的验证码是否有效",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Verification"
                ],
                "summary": "验证验证码",
                "parameters": [
                    {
                        "description": "邮箱和验证码",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.VerifyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "通信成功（通过code来判断具体情况）",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.VerificationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.VerifyToken": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.Asset": {
            "type": "object",
            "properties": {
                "file_id": {
                    "description": "文件标识符",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "name": {
                    "description": "资源名称",
                    "type": "string"
                }
            }
        },
        "models.Question": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.Song": {
            "type": "object",
            "properties": {
                "file_id": {
                    "description": "文件标识符",
                    "type": "string"
                },
                "id": {
                    "description": "主键",
                    "type": "integer"
                },
                "title": {
                    "description": "歌曲标题",
                    "type": "string"
                }
            }
        },
        "request.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request.ScoreRequest": {
            "type": "object",
            "properties": {
                "song_id": {
                    "type": "integer"
                },
                "total_score": {
                    "type": "integer"
                }
            }
        },
        "request.VerifyRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "response.AssetResponse": {
            "type": "object",
            "properties": {
                "asset_id": {
                    "type": "string"
                }
            }
        },
        "response.AssetsResponse": {
            "type": "object",
            "properties": {
                "asset_ids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Asset"
                    }
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "response.ScoreReponse": {
            "type": "object",
            "properties": {
                "score": {
                    "type": "integer"
                },
                "song_title": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "response.SongResponse": {
            "type": "object",
            "properties": {
                "song_id": {
                    "type": "string"
                }
            }
        },
        "response.SongsResponse": {
            "type": "object",
            "properties": {
                "song_ids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Song"
                    }
                }
            }
        },
        "response.UploadToken": {
            "type": "object",
            "properties": {
                "upload_token": {
                    "type": "string"
                }
            }
        },
        "response.VerificationResponse": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "NeedForTyping",
	Description:      "一个打字游戏",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
